FPS = 60

BACKGROUND_COLOR = '#FFFFFF'
DRAWING_COLOR = '#00FF00'
ERASER_COLOR = BACKGROUND_COLOR
LONG_PRESS_DURATION = 0.5
DOUBLE_CLICK_THRESHOLD = 0.2

POINTER_SIZE = 50
UI_LINE_WIDTH = int(POINTER_SIZE / 10)
DRAWING_WIDTH = int(POINTER_SIZE / 5)
ERASER_WIDTH = int(POINTER_SIZE * 2)
LINE_WIDTH = DRAWING_WIDTH

ICON_DIRECTORY = 'icons/'
ICON_SIZE = 150
ICON_TINT = DRAWING_COLOR
ICON_DURATION = 0.5